### ISSUE TITLE
add License

### ISSUE THREAD

**Issue by bedroesb** [ELIXIR-Belgium/data_management_hub#38]

**Comment by floradanna** [comment]
"Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/); all the material under this licence can be freely used, as long as ELIXIR Belgium [DM Hub](https://rdm.elixir-belgium.org/index.html) is credited as the author".


<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Data Management Hub</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://rdm.elixir-belgium.org/index.html" property="cc:attributionName" rel="cc:attributionURL">ELIXIR Belgium</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
